ci: make release testing depend on tests passing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,12 +5,10 @@ concurrency:
   cancel-in-progress: true
 
 on:
-  push: 
-    branches:
-      - main
-  pull_request: 
-    branches:
-      - main
+  workflow_run:
+    workflows: [Tests and formatting]
+    types: [completed]
+    
 env:
   CARGO_TERM_COLOR: always
 
@@ -18,6 +16,7 @@ jobs:
   release_compile:
     name: ReleaseCompile
     runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - uses: wykies/checkout@main
       - uses: wykies/setup-rust-toolchain@main
@@ -25,3 +24,9 @@ jobs:
         run: cargo run --bin switch-db -- standalone
       - name: Run Release Compile
         run: cargo check --all-features --release
+  on-failure:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+    steps:
+      - run: echo 'The triggering workflow failed'
+      - run: exit 1
